Language: java
Jdk: 
  - oraclejdk8
  - oraclejdk9
  - openjdk8

services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE controlescolar;'
  
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use openjdk8
  - # do stuff with open Java 8
